config/routes.rb
Rails.application.routes.draw do
  get "cumulative", to: "areas#cumulative"
  get "daily", to: "areas#daily"
  get "average", to: "areas#average"

  namespace "admin" do
    resources :hits, only: :index
  end

  root to: "areas#cumulative"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area
  def self.from_json(json)
    json.map do |code, data|
      name = data['name']['value']
      cumulative_counts = data['dailyTotalConfirmedCases']
      daily_counts = data['dailyConfirmedCases']

      Area.new(code, name, cumulative_counts, daily_counts)
    end
  end

  def initialize(code, name, cumulative_counts, daily_counts)
    @code = code
    @name = name
    @cumulative_counts = format_counts(cumulative_counts)
    @daily_counts = format_counts(daily_counts)
  end

  def name
    ALIASES.fetch(@name, @name)
  end

  attr_reader :daily_counts, :cumulative_counts, :code

  def rolling_average_daily_counts
    @rolling_average_daily_counts ||= calculate_rolling_average_daily_counts
  end

  private

  ALIASES = {
    'Bristol, City of' => 'Bristol',
    'Kingston upon Hull, City of' => 'Kingston upon Hull'
  }.freeze

  def calculate_rolling_average_daily_counts
    daily_counts.keys.map do |date|
      sample_start = date - 2.days
      sample_end = date
      range = sample_start..sample_end

      sample = daily_counts.select { |date_key| date_key.in?(range) }
      average_count = sample.values.sum / sample.size

      [date, average_count]
    end.to_h
  end

  def format_counts(counts)
    counts.map do |count|
      [Date.parse(count['date']), count['value']]
    end.to_h
  end
end

app/models/data_source.rb
module DataSource
  HOST = 'https://c19downloads.azureedge.net'.freeze
  PATH = '/downloads/data/utlas_latest.json'.freeze

  class << self
    def connection
      Faraday.new(url: HOST) do |faraday|
        faraday.response :json
        faraday.adapter Faraday.default_adapter
      end
    end

    def to_json
      Rails.cache.fetch('data_source_cache', expires_in: 1.hour) do
        connection.get(PATH).body
      end
    end

    def utlas_json
      to_json.except("metadata")
    end
  end
end

app/models/visit_event.rb
class VisitEvent < ApplicationRecord
end

app/controllers/admin/hits_controller.rb
class Admin::HitsController < ApplicationController
  skip_after_action :track_action

  layout "admin"

  def index
    @hits = VisitEvent.group_by_day(:created_at).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  after_action :track_action, unless: :ignored_ip_address?

  def track_action
    VisitEvent.create(controller_name: controller_name, action_name: action_name)
  end

  def ignored_ip_address?
    request.remote_ip == ENV['IGNORED_IP']
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def cumulative
    @areas = set_areas
    @area = find_area(@areas)
  end

  def daily
    @areas = set_areas
    @area = find_area(@areas)
  end

  def average
    @areas = set_areas
    @area = find_area(@areas)
  end

  private

  def set_areas
    Area.from_json(utlas_json).sort_by(&:name)
  end

  def find_area(areas)
    areas.find { |area| area.code == area_code }
  end

  def area_code
    params.fetch(:area_code, 'E06000023')
  end

  def utlas_json
    DataSource.utlas_json
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def cumulative
    @areas = set_areas
    @area = find_area(@areas)
  end

  def daily
    @areas = set_areas
    @area = find_area(@areas)
  end

  private

  def set_areas
    Area.from_utlas(utlas).sort_by(&:name)
  end

  def find_area(areas)
    areas.find { |area| area.code == area_code }
  end

  def area_code
    params.fetch(:area_code, 'E06000023')
  end

  def utlas
    Spreadsheet.covid_19.utlas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/hits/index.html.erb
<div class="chart-container">
  <%= column_chart @hits, ytitle: "Hits", height: "100%" %>
</div>

app/views/areas/average.html.erb
<div class="chart-container">
  <p>Rolling three day average confirmed cases - <%= @area.name %></p>

  <%= column_chart @area.rolling_average_daily_counts, ytitle: "Average Confirmed Cases", height: "100%" %>

  <p>Average daily case counts are a rolling three day average of <%= link_to 'daily case counts', daily_path(area_code: @area.code) %>. People who have recovered and those who have died are included in the counts.</p>
</div>

app/views/areas/cumulative.html.erb
<div class="chart-container">
  <p>Cumulative confirmed COVID-19 cases - <%= @area.name %></p>

  <%= line_chart @area.cumulative_counts, ytitle: "Confirmed Cases", height: "100%" %>

  <p>Daily cumulative case counts are those that were published each day on the PHE Dashboard. People who have recovered and those who have died are included in the cumulative counts.</p>
</div>

app/views/areas/daily.html.erb
<div class="chart-container">
  <p>Daily confirmed COVID-19 cases - <%= @area.name %></p>

  <%= column_chart @area.daily_counts, ytitle: "Confirmed Cases", height: "100%" %>

  <p>Daily case counts are those that were published each day on the PHE Dashboard. People who have recovered and those who have died are included in the counts.</p>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @area.name %> COVID-19 cases</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <%= form_tag({}, {method: :get}) do |f| %>
        <div class=’form-group’>
          <%= select_tag("area_code", options_from_collection_for_select(@areas, :code, :name, @area.code), onchange: "this.form.submit()") %>
          <noscript>
            <%= submit_tag("filter") %>
        </noscript>
        </div>
      <% end %>

      <ul class="nav-bar">
        <li>
          <%=
            link_to_unless controller.action_name == "cumulative",
            'Cumulative',
            cumulative_path(area_code: @area.code)
          %>
        </li>
        <li>
          <%=
            link_to_unless controller.action_name == "daily",
            'Daily',
            daily_path(area_code: @area.code)
          %>
        </li>
        <li>
          <%=
            link_to_unless controller.action_name == "average",
            'Average',
            average_path(area_code: @area.code)
          %>
        </li>
      </ul>
    </header>


    <div style="clear: both;"></div>

    <%= yield %>
  </body>
</html>